// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_subpath_ from './routes/[...subpath].ts';
import * as $_404 from './routes/_404.ts';
import * as $_middleware from './routes/_middleware.ts';
import * as $index from './routes/index.ts';

import { type Manifest } from '$fresh/server.ts';

const manifest = {
  routes: {
    './routes/[...subpath].ts': $_subpath_,
    './routes/_404.ts': $_404,
    './routes/_middleware.ts': $_middleware,
    './routes/index.ts': $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
